"""Generate per-tenant docker-compose and app .env from a tenant input file.

Usage:
    poetry run gen-tenant tenants/<tenant>.env [--force]

Outputs (written at repo root):
    docker-compose.<tenant>.yml   parameterized infra stack
    .env.<tenant>                 consumed by FastAPI via pydantic-settings
    ./volumes/<tenant>/{etcd,minio,milvus,redis}   bind-mount roots

After generation:
    docker compose -f docker-compose.<tenant>.yml -p <tenant> up -d
    ln -sf .env.<tenant> .env
    poetry run start
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

MINIO_API_PORT_BASE = 9002
MINIO_CONSOLE_PORT_BASE = 9003
MILVUS_GRPC_PORT_BASE = 19531
MILVUS_HEALTH_PORT_BASE = 9092
REDIS_PORT_BASE = 6379
APP_PORT_BASE = 8001

PORT_OFFSET_STEP = 100
PORT_OFFSET_MAX = 9000

TENANT_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]*$")

SERVICE_VOLUME_NAMES: tuple[str, ...] = ("etcd", "minio", "milvus", "redis")

DEFAULT_MINIO_ACCESS_KEY = "minioadmin"
DEFAULT_MINIO_SECRET_KEY = "minioadmin"  # noqa: S105
DEFAULT_MINIO_BUCKET_NAME = "rag-storage"
DEFAULT_APP_ENV = "dev"
DEFAULT_MINIO_SECURE = "false"
DEFAULT_MINIO_PUBLIC_SECURE = "true"
DEFAULT_HOST = "localhost"

CARRY_THROUGH_PREFIXES: tuple[str, ...] = ("LLM__", "DOC_PARSER__", "KEYCLOAK__")
MILVUS_CARRY_THROUGH_KEYS: tuple[str, ...] = (
    "MILVUS__CORPUS_COLLECTION_NAME",
    "MILVUS__INPUT_COLLECTION_NAME",
    "MILVUS__VECTOR_DIM",
    "MILVUS__METRIC_TYPE",
)


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        raise FileNotFoundError(f"Tenant input file not found: {path}")

    out: dict[str, str] = {}
    with path.open("r", encoding="utf-8") as fh:
        for line_num, raw_line in enumerate(fh, start=1):
            stripped = raw_line.strip()
            if not stripped or stripped.startswith("#"):
                continue

            if "=" not in stripped:
                raise ValueError(f"{path}:{line_num}: expected KEY=VALUE, got: {raw_line.rstrip()}")

            key, _, value = stripped.partition("=")
            key = key.strip()
            value = value.strip()

            if len(value) >= 2 and value[0] in ("'", '"') and value[-1] == value[0]:
                value = value[1:-1]

            out[key] = value

    return out


def validate_tenant_id(value: str) -> str:
    if not TENANT_ID_PATTERN.match(value):
        raise ValueError(f"Invalid TENANT_ID '{value}': must match {TENANT_ID_PATTERN.pattern}")
    return value


def validate_port_offset(value: str) -> int:
    try:
        offset = int(value)
    except ValueError as exc:
        raise ValueError(f"PORT_OFFSET must be an integer, got '{value}'") from exc

    if offset < 0 or offset > PORT_OFFSET_MAX:
        raise ValueError(f"PORT_OFFSET out of range [0..{PORT_OFFSET_MAX}]: {offset}")

    if offset % PORT_OFFSET_STEP != 0:
        raise ValueError(f"PORT_OFFSET must be a multiple of {PORT_OFFSET_STEP}: {offset}")

    return offset


# TODO: render_compose() is 66+ lines and exceeds the 50-line limit (Coding conventions §5).
#       Refactor by extracting the multi-line f-string into a template file or helper function.
def render_compose(
    tenant_id: str,
    port_offset: int,
    minio_access_key: str,
    minio_secret_key: str,
) -> str:
    minio_api_host = MINIO_API_PORT_BASE + port_offset
    minio_console_host = MINIO_CONSOLE_PORT_BASE + port_offset
    milvus_grpc_host = MILVUS_GRPC_PORT_BASE + port_offset
    milvus_health_host = MILVUS_HEALTH_PORT_BASE + port_offset
    redis_host = REDIS_PORT_BASE + port_offset

    return f"""# Generated by api/scripts/gen_tenant_stack.py — do not hand-edit.
# Tenant: {tenant_id}    Port offset: {port_offset}
version: "3.5"

services:
  etcd:
    container_name: {tenant_id}-milvus-etcd
    image: quay.io/coreos/etcd:v3.5.25
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/{tenant_id}/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: {tenant_id}-milvus-minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: {minio_access_key}
      MINIO_SECRET_KEY: {minio_secret_key}
      # Open CORS for browser-side presigned downloads. Presigned URLs already
      # carry the access capability; origin restriction adds no real security.
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "{minio_console_host}:9001"
      - "{minio_api_host}:9000"
    volumes:
      - ./volumes/{tenant_id}/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: {tenant_id}-milvus-standalone
    image: milvusdb/milvus:v2.6.11
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ./volumes/{tenant_id}/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "{milvus_grpc_host}:19530"
      - "{milvus_health_host}:9091"
    depends_on:
      - "etcd"
      - "minio"

  redis:
    container_name: {tenant_id}-redis
    image: redis/redis-stack-server:latest
    ports:
      - "{redis_host}:6379"
    volumes:
      - ./volumes/{tenant_id}/redis:/data
    restart: always

networks:
  default:
    name: {tenant_id}-milvus
"""


# TODO: render_app_env() violates two limits (Coding conventions §5): 57+ lines (exceeds 50)
#       and 9 parameters (exceeds 5). Use a dataclass to bundle the ports/credentials and
#       reduce parameters.
def render_app_env(
    tenant_id: str,
    port_offset: int,
    input_vars: dict[str, str],
    minio_access_key: str,
    minio_secret_key: str,
    minio_bucket_name: str,
    milvus_host: str,
    minio_host: str,
    redis_host: str,
    minio_public_endpoint: str | None,
    minio_public_secure: str | None,
) -> str:
    minio_api_host_port = MINIO_API_PORT_BASE + port_offset
    milvus_grpc_host_port = MILVUS_GRPC_PORT_BASE + port_offset
    redis_host_port = REDIS_PORT_BASE + port_offset
    app_port = APP_PORT_BASE + port_offset

    lines: list[str] = [
        "# Generated by api/scripts/gen_tenant_stack.py — do not hand-edit.",
        f"# Tenant: {tenant_id}    Port offset: {port_offset}",
        "",
        f"APP_ENV={input_vars.get('APP_ENV', DEFAULT_APP_ENV)}",
        f"APP_PORT={app_port}",
        "",
        "# Milvus (host-side connection)",
        f"MILVUS__HOST={milvus_host}",
        f"MILVUS__PORT={milvus_grpc_host_port}",
    ]

    for key in MILVUS_CARRY_THROUGH_KEYS:
        if key in input_vars:
            lines.append(f"{key}={input_vars[key]}")

    lines.extend(
        [
            "",
            "# MinIO (host-side connection)",
            f"MINIO__ENDPOINT={minio_host}:{minio_api_host_port}",
            f"MINIO__ACCESS_KEY={minio_access_key}",
            f"MINIO__SECRET_KEY={minio_secret_key}",
            f"MINIO__BUCKET_NAME={minio_bucket_name}",
            f"MINIO__SECURE={input_vars.get('MINIO__SECURE', DEFAULT_MINIO_SECURE)}",
        ]
    )

    if minio_public_endpoint:
        lines.append(f"MINIO__PUBLIC_ENDPOINT={minio_public_endpoint}")
        lines.append(f"MINIO__PUBLIC_SECURE={minio_public_secure or DEFAULT_MINIO_PUBLIC_SECURE}")

    lines.extend(
        [
            "",
            "# Redis (host-side connection)",
            f"REDIS__REDIS_URL=redis://{redis_host}:{redis_host_port}",
            "",
        ]
    )

    section_labels = {
        "LLM__": "# LLM",
        "DOC_PARSER__": "# Document parser",
        "KEYCLOAK__": "# Keycloak",
    }
    for prefix in CARRY_THROUGH_PREFIXES:
        carried = {k: v for k, v in input_vars.items() if k.startswith(prefix)}
        if not carried:
            continue
        lines.append(section_labels[prefix])
        for key in sorted(carried):
            lines.append(f"{key}={carried[key]}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def create_volume_dirs(repo_root: Path, tenant_id: str) -> None:
    base = repo_root / "volumes" / tenant_id
    for service_name in SERVICE_VOLUME_NAMES:
        (base / service_name).mkdir(parents=True, exist_ok=True)


def print_next_steps(tenant_id: str) -> None:
    project_arg = f"-p {tenant_id}"
    file_arg = f"-f docker-compose.{tenant_id}.yml"
    print()
    print(f"Generated stack files for tenant '{tenant_id}'. Next steps:")
    print()
    print(f"  docker compose {file_arg} {project_arg} up -d")
    print(f"  ln -sf .env.{tenant_id} .env")
    print("  poetry run start")
    print()
    print("To tear down:")
    print(f"  docker compose {file_arg} {project_arg} down")
    print()


# TODO: main() is 83+ lines and exceeds the 50-line limit (Coding conventions §5).
#       Extract validation logic (lines 293–315) and file generation (lines 340–363) into
#       separate functions.
def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    parser = argparse.ArgumentParser(
        description="Generate per-tenant docker-compose and .env files.",
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Path to tenants/<tenant>.env input file.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing output files if present.",
    )
    args = parser.parse_args(argv)

    try:
        input_vars = parse_env_file(args.input)
    except (FileNotFoundError, ValueError) as exc:
        logger.error(str(exc))
        return 1

    if "PORT_OFFSET" not in input_vars:
        logger.error("Required key missing in input: PORT_OFFSET")
        return 1

    stem = args.input.stem
    if stem == "example":
        logger.error("tenants/example.env is a template — copy it first:\n  cp tenants/example.env tenants/<your-tenant>.env")
        return 1

    file_tenant_id = input_vars.get("TENANT_ID")
    if file_tenant_id is not None and file_tenant_id != stem:
        logger.error(
            f"Tenant ID mismatch: filename stem is '{stem}' but TENANT_ID='{file_tenant_id}'.\nRecommended: drop TENANT_ID from the input file — it's now derived from the filename."
        )
        return 1

    try:
        tenant_id = validate_tenant_id(stem)
        port_offset = validate_port_offset(input_vars["PORT_OFFSET"])
    except ValueError as exc:
        logger.error(str(exc))
        return 1

    repo_root = Path.cwd()
    compose_path = repo_root / f"docker-compose.{tenant_id}.yml"
    env_path = repo_root / f".env.{tenant_id}"

    if not args.force:
        existing = [p for p in (compose_path, env_path) if p.exists()]
        if existing:
            joined = "\n  ".join(str(p) for p in existing)
            logger.error(f"Refusing to overwrite existing files (use --force):\n  {joined}")
            return 1

    minio_access_key = input_vars.get("MINIO_ACCESS_KEY", DEFAULT_MINIO_ACCESS_KEY)
    minio_secret_key = input_vars.get("MINIO_SECRET_KEY", DEFAULT_MINIO_SECRET_KEY)
    minio_bucket_name = input_vars.get("MINIO_BUCKET_NAME", DEFAULT_MINIO_BUCKET_NAME)
    milvus_host = input_vars.get("MILVUS_HOST", DEFAULT_HOST) or DEFAULT_HOST
    minio_host = input_vars.get("MINIO_HOST", DEFAULT_HOST) or DEFAULT_HOST
    redis_host = input_vars.get("REDIS_HOST", DEFAULT_HOST) or DEFAULT_HOST
    minio_public_endpoint = input_vars.get("MINIO_PUBLIC_ENDPOINT") or None
    minio_public_secure = input_vars.get("MINIO_PUBLIC_SECURE") or None

    compose_text = render_compose(
        tenant_id,
        port_offset,
        minio_access_key,
        minio_secret_key,
    )
    env_text = render_app_env(
        tenant_id,
        port_offset,
        input_vars,
        minio_access_key,
        minio_secret_key,
        minio_bucket_name,
        milvus_host,
        minio_host,
        redis_host,
        minio_public_endpoint,
        minio_public_secure,
    )

    try:
        compose_path.write_text(compose_text, encoding="utf-8")
        env_path.write_text(env_text, encoding="utf-8")
        create_volume_dirs(repo_root, tenant_id)
    except OSError as exc:
        logger.error(f"Failed to write tenant stack files: {exc}")
        for partial in (compose_path, env_path):
            if partial.exists():
                try:
                    partial.unlink()
                except OSError:
                    logger.warning(f"Could not clean up partial file: {partial}")
        return 1

    logger.info(f"Wrote {compose_path.relative_to(repo_root)}")
    logger.info(f"Wrote {env_path.relative_to(repo_root)}")
    logger.info(f"Created ./volumes/{tenant_id}/{{{','.join(SERVICE_VOLUME_NAMES)}}}")
    print_next_steps(tenant_id)
    return 0


if __name__ == "__main__":
    sys.exit(main())
